### ISSUE TITLE
Cannot override I18n message. Readme instructions are wrong.

### ISSUE THREAD

**Issue by monfresh** [hallelujah/valid_email#57]
Hi. I just installed this gem, and added the following validation to my `User` model:

```ruby
validates :email,
          email: {
            mx: true,
            message: I18n.t('validations.errors.models.user.invalid_email')
          }
```

I then added the following entry in my `en.yml`:
```yaml
validations:
  errors:
    models:
      user:
        invalid_email: 'Custom message'
```

However, when I enter an invalid email for a User, I always get `is invalid` as the error message. So then, I did a search for `is invalid` in this repo, and found that the gem is using this I18n entry:

```yaml
valid_email:
  validations:
    email:
      invalid: "is invalid"
```

Ideally, we should be able to use any message we want in the model validation, for example:

```ruby
validates :email,
          email: {
            mx: true,
            message: 'Custom message goes here'
          }
```

If that's not possible, then the documentation must be updated to say that you need to use the same I18n entry as the one this gem uses: `I18n.t('valid_email.validations.email.invalid')`.

Thanks!
